name: ci
inputs:
  dockerfile-target:
    description: 'Dockerfile target name'
    required: true
  image-tag:
    description: 'Docker image tag name'
    required: true
runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
  - run: eval "$(ssh-agent -s)" && export DOCKER_BUILDKIT=1 && docker build --target ${{inputs.dockerfile-target}} -t ${{inputs.image-tag}} .
    shell: bash
  - run: docker run --rm -v ${{ github.workspace }}:/app -v $SSH_AUTH_SOCK:$SSH_AUTH_SOCK -e SSH_AUTH_SOCK ${{inputs.image-tag}}
    shell: bash
