on:
    pull_request:
    push:
      branches-ignore:
        - main
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Action self-test
        uses: ./
        with:
          dockerfile-target: python-target
          image-tag: python-tag
