on:
    pull_request:
    push:

jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: abatilo/actions-poetry@v2
      - name: Action self-test
        uses: ./
