on:
    pull_request:
      branches-ignore:
        - main
    push:

jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Action self-test
        uses: ./
